### ISSUE TITLE
Swagger not working in 4.2.0

### ISSUE THREAD

**Issue by desarrollo-ctme** [dj-nitehawk/FastEndpoints#122]
Greetings:
   
   Today I noticed there was a new version of this awesome library and installed it right away. Just after that my API refused to start, giving me this trace error:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(IServiceProvider provider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor..ctor()
   at FastEndpoints.Swagger.Extensions.EnableFastEndpoints(AspNetCoreOpenApiDocumentGeneratorSettings settings, Int32 tagIndex, Int32 maxEndpointVersion, Boolean shortSchemaNames)
   at FastEndpoints.Swagger.Extensions.<>c__DisplayClass2_0.<AddSwaggerDoc>b__0(AspNetCoreOpenApiDocumentGeneratorSettings s)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass0_0.<AddOpenApiDocument>b__0(AspNetCoreOpenApiDocumentGeneratorSettings settings, IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass1_0.<AddOpenApiDocument>b__0(AspNetCoreOpenApiDocumentGeneratorSettings settings, IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass3_0.<AddSwaggerDocument>b__0(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.NSwagApplicationBuilderExtensions.UseOpenApiWithApiExplorerCore(IApplicationBuilder app, Action`1 configure)
   at Microsoft.AspNetCore.Builder.NSwagApplicationBuilderExtensions.UseOpenApi(IApplicationBuilder app, Action`1 configure)
   at Program.<Main>$(String[] args) 
```

   
   The execution stops at:
   app.UseOpenApi();
   
   If I remove:     
	   app.UseOpenApi();  
	   app.UseSwaggerUi3();

   the api starts and works just fine, this is swagger related only, I think.
   
  Maybe the fault is in my end? Going back to 4.1.0 fixes the problem without changing any code.
   
   Best Regards.

**Comment by NeskireDK** [comment]
@desarrollo-ctme Have you tried a complete clean and rebuild? 
I had a similar issue, went away after clean and force restore nuget packages.

**Comment by desarrollo-ctme** [comment]
Already tried, also cleaning bin and obj folders, same result. Just downgrading  FastEndpoints.Swagger package to  4.1.0 is enough to get it running again, but I guess that mismatching version packages is not recommended.

**Comment by wjax** [comment]
Could you provide a repo with an example of the problem?

**Comment by dj-nitehawk** [comment]
@desarrollo-ctme & @wjax 
i believe i've figured out what's happening.
most likely you're calling `app.UseOpenApi()` before calling `app.UseFastEndpoints()` like so:
```csharp
var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseOpenApi();
app.UseFastEndpoints(); //this reproduces the null reference exception - move this up to fix the issue
app.UseSwaggerUi3(s => s.ConfigureDefaults());
app.Run();
```
i will add better checks against this and throw a proper error message when the pipeline is configured incorrectly like this.

if that doesn't solve it for you, please do a repo that has the problem so we can clone it and debug.

thanks!

**Comment by desarrollo-ctme** [comment]
So it seems I've had the pipeline configured incorrectly this whole time, but it worked just fine until 4.2.0. My fault then, sorry.
Thanks @dj-nitehawk  for the solution,  as always.

**Comment by dj-nitehawk** [comment]
no worries mate... it's just the new fluentvalidation+swagger integration relies on being able to get access to the DI container. it was not needed before. all good then...
