### ISSUE TITLE
Add possibility to get an array from query parameter the usual way

### ISSUE THREAD

**Issue by maxreb** [dj-nitehawk/FastEndpoints#165]
Hi,

Currently fast-endpoints needs array to be json formatted when received from query like so: 
`/my-endpoint?Codes=[1,2,3]`

This makes swagger not functional and consumers irritated.  The default way is actually that arrays will be passed like this:
`/my-endpoint?Codes=1&Codes=2&Codes=3`
but currently this will set the array to `null` 

The dto:
```
public class MyEndpointRequest {
    public int[] Codes {get; set; }
}
```

Is it possible to implement this standard in fast-endpoints, too? 

p.s.: thank you very much for this amazing project, I really appreciate it!

**Comment by dj-nitehawk** [comment]
implemented in `v4.4.0-beta1`
give it a shot and report back pls
thanks!

**Comment by maxreb** [comment]
Wow, not only your endpoints are fast :D Thanks a lot!
It works very well with an `int array` but does not seem to work with a `string array` yet:

```
System.Text.Json.JsonException: 's' is an invalid start of a value. Path: $[0] | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.Text.Json.JsonReaderException: 's' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at FastEndpoints.ReflectionExtensions.TryDeserializeArrayString(Object input, Type type, Object& result)
   at FastEndpoints.ReflectionExtensions.<>c__DisplayClass8_0.<GetCompiledValueParser>b__3(Object input)
   at FastEndpoints.Endpoint`2.Bind(TRequest req, KeyValuePair`2 kvp, List`1 failures)
   at FastEndpoints.Endpoint`2.BindQueryParams(TRequest req, IQueryCollection query, List`1 failures)
   at FastEndpoints.Endpoint`2.BindToModel(HttpContext ctx, List`1 failures, JsonSerializerContext serializerCtx, Boolean dontAutoBindForm, CancellationToken cancellation)
   at FastEndpoints.Endpoint`2.ExecAsync(HttpContext ctx, EndpointDefinition endpoint, CancellationToken cancellation)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by dj-nitehawk** [comment]
fixed in `v4.4.0-beta2`
there was an oversight in the [test](https://github.com/dj-nitehawk/FastEndpoints/blob/b5542d3bf0492907beb87863416b4b82b59995ce/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/MiscTestCases.cs#L247-L271) i wrote ;-)
should be fine now...

**Comment by maxreb** [comment]
Great, strings work now, too. 
If you type as first string something like `["1","2"]` you would still get an array as it will be parsed as JSON, or worse if you type in `[1,2]` as first array you will get an Exception:
 > System.Text.Json.JsonException: The JSON value could not be converted to System.String[]. Path: $[0] | LineNumber: 0 | BytePositionInLine: 2.

![image](https://user-images.githubusercontent.com/39700092/180386865-e89332e2-fdc2-469d-a567-d360115e9220.png)


I do understand that removing this would be a breaking change but it could also lead to confusion. Is there a good reason to keep the JSON Array parsing thingy, that I don't see right now?

**Comment by dj-nitehawk** [comment]
ok, third time's the charm ;-)
try `v4.4.0-beta3`
can't really remove the json deserialization support because sometime back we had a lengthy about this and some people didn't like the norm of having duplicate query parameters and how the standard way seems weird.
now people have a choice since both methods are supported.

**Comment by maxreb** [comment]
Ah okay, I see. It reminds me a little bit of this [xkcd #927](https://xkcd.com/927/) :D 
Then, if I understand your point correctly this error is by design?
![image](https://user-images.githubusercontent.com/39700092/180409625-05ec7a90-8650-450f-8e84-e1fc750ae944.png)

Thanks for your fantastic work again, I donated a little bit and looking forward to support your framework, so if you need any help I can surely contribute :)

**Comment by dj-nitehawk** [comment]
that's supposed to work with `v4.4.0-beta3`.
see the [test here](https://github.com/dj-nitehawk/FastEndpoints/blob/77d9e3af28d3d730c92b66db11821ab2510842e4/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/MiscTestCases.cs#L257)

received the donation. greatly appreciated 🙏

if you're interested in contributing, do join our [discord server](https://discord.gg/yQZ4uvfF2E) since most of the action happens there. also you can have a look at any of the gh issues labeled as `up for grabs`.

**Comment by maxreb** [comment]
`[1,2]` does work but `["1","2"]` (with quotes) doesn't. But if you say you wan't to let people choose whether they use JSON or the standard way, I think we have to live with it, or? Other possibility could be, that one can set it up in the `UseFastEndpoints()` method.

```
app.UseFastEndpoints(o => o.QueryArrayWithJson = true/false); //something like this?
```

Great, I joined the discord server and if I find some time I take a look at the issues :)

**Comment by dj-nitehawk** [comment]
try `v4.4.0-beta5`
i think i finally nailed it :-)

the thing is we have to rely on STJ for the creation of different types of object graphs that are to be assigned to the `IEnumerable` properties. otherwise we'd have to re-invent a massive wheel.

**Comment by maxreb** [comment]
Yes, works like a charm, thanks a lot :)
