### ISSUE TITLE
Exception when settings version info without prefix

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#33]
From the Web sample in the repo:

```
app.UseFastEndpoints(config =>
{
    config.SerializerOptions = o => o.PropertyNamingPolicy = null;
    config.EndpointRegistrationFilter = ep => ep.Tags?.Contains("exclude") is not true;
   // config.RoutingOptions = o => o.Prefix = "api";
    config.VersioningOptions = o =>
    {
        o.Prefix = "v";
        o.DefaultVersion = 1;
        o.SuffixedVersion = false;
    };
}); //must go before useendpoints if that call is present.
```

Will throw exception

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at FastEndpoints.MainExtensions.<BuildRoute>g__AppendVersion|4_0(StringBuilder builder, Int32 epVersion, Boolean trailingSlash) in ... FastEndpoints/Src/Library/Extensions/MainExtensions.cs:line 171
```

If RoutingOptions is uncomment then it works.

**Comment by stefandevo** [comment]
Possible related to #34 #35

**Comment by dj-nitehawk** [comment]
good catch! fixed...
