### ISSUE TITLE
FastEndpoint Patch vs JsonPatchDocument

### ISSUE THREAD

**Issue by philippemercure** [dj-nitehawk/FastEndpoints#77]
Hello, I'm wondering if you could provide an example of a Patch Endpoint. I can't figure how to do a Patch Endpoint with FastEndpoint. I was able to use a Controller with JsonPatchDocument, but it's not as clean a the other Features I'm using with FastEndpoint. And I would prefer to skip the use of a Controller if FastEndpoint support the Patch verb.

# With a Controller

```c#
[ApiController]
[Route("[controller]")]
public class UserController : ControllerBase
{
    [HttpPatch]
    public Shared.Entities.User PatchJsonDocument(Guid userIdentification, JsonPatchDocument<Shared.Entities.UserPatch> userModel)
    {
        var newUserModel = new Shared.Entities.User
        {
            FirstName = "Your",
            LastName = "Name"
        };

        userModel.ApplyTo(newUserModel);

        return newUserModel;
    }
}
```

# With FastEndpoint (Standard)

This is working, but it required to manually map to the JsonPatchDocument and the endpoint caller can't specify what he wants to do with each object properties (add, replace, remove, ...).

```c#
public class EndpointStandard : Endpoint<Model.Request, Model.Response, Mapper>
{
    public override void Configure()
    {
        Options(x => x.WithTags("user"));
        Patch("client/user");
        Version(1);
        AllowAnonymous();
        Summary(new EndpointSummary
        {
            Summary = "Patch partially one user",
            Description = "This endpoint is use to patch one user in the database"
        });
    }
    
    public override async Task HandleAsync(Model.Request request, CancellationToken cancellationToken)
    {
        var jsonPatch = new JsonPatchDocument<UserPatch>().Replace(x => x.FirstName, request.FirstName);
        
        var logicUser = new Shared.Entities.User
        {
            FirstName = "Your",
            LastName = "Name"
        };

        jsonPatch.ApplyTo(logicUser);
        
        var user = Map.FromEntity(logicUser);
            
        await SendAsync(user, cancellation: cancellationToken);
       
    }
}
```

# With FastEndpoint (JsonPatchDocument)

If I try to use the JsonPatchDocument object in FastEndpoint class.

```c#
public class EndpointJsonPatchDocument : Endpoint<JsonPatchDocument<UserPatch>, Model.Response, Mapper>
{
    public override void Configure()
    {
        Options(x => x.WithTags("user"));
        Patch("client/user2");
        Version(1);
        AllowAnonymous();
        Summary(new EndpointSummary
        {
            Summary = "Patch partially one user",
            Description = "This endpoint is use to patch one user in the database"
        });
    }
    
    public override async Task HandleAsync(JsonPatchDocument<UserPatch> request, CancellationToken cancellationToken)
    {
        var logicUser = new Shared.Entities.User
        {
            FirstName = "Your",
            LastName = "Name"
        };

        request.ApplyTo(logicUser);
        
        var user = Map.FromEntity(logicUser);
            
        await SendAsync(user, cancellation: cancellationToken);
    }
}
```

I'm getting this error when I call the endpoint like this.

```http
PATCH /client/user2/v1 HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Content-Length: 126

{
    [
        {
            "path" : "/firstName",
            "op" : "replace",
            "value": "Yo"
        }
    ]
}
```

And I'm not even hitting the breakpoint I set on the line logicUser inside HandleAync

```c#
public override async Task HandleAsync(JsonPatchDocument<UserPatch> request, CancellationToken cancellationToken)
    {
        var logicUser = new Shared.Entities.User
```

The error in console

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 PATCH http://localhost:5000/client/user2/v1 application/json 126


fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMGG4RBVM0DU", Request id "0HMGG4RBVM0DU:00000005": An unhandled exception was thrown by the application.
      System.Text.Json.JsonException: '[' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 1 | BytePositionInLine: 4.
       ---> System.Text.Json.JsonReaderException: '[' is an invalid start of a property name. Expected a '"'. LineNumber: 1 | BytePositionInLine: 4.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
         at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at FastEndpoints.Endpoint`2.BindToModel(HttpContext ctx, List`1 failures, JsonSerializerContext serializerCtx, CancellationToken cancellation)
         at FastEndpoints.Endpoint`2.ExecAsync(HttpContext ctx, EndpointDefinition endpoint, CancellationToken cancellation)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)


info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 PATCH http://localhost:5000/client/user2/v1 application/json 126 - 500 0 - 6.1978ms

```

It seem that FastEndpoint is not using the JsonPatchDocument correctly. Or I didn't setup the pipeline correctly.

My pipeline setup

```c#
webApplicationBuilder.Services
    .AddFastEndpoints()
    .AddSwaggerDocCustom(sharedSettings, 1, 1);

// Needed to make the Patch endpoint work in the Controllers
webApplicationBuilder.Services.AddControllers().AddNewtonsoftJson();

webApplication
    .UseFastEndpoints()
    .UseAuthorization()
    .UseOpenApi()
    .UseSwaggerUi3();

// Needed to make the Patch endpoint work in the Controllers
webApplication.UseHttpsRedirection();
webApplication.UseAuthorization();
webApplication.MapControllers();
```

Waitings news.

Thanks a lot.

**Comment by dj-nitehawk** [comment]
jsonpatch is currently not yet supported by .net 6 minimal api and in turn not supported by fastendpoints since we're based on minimal apis. need to wait until minimap api for jsonpatch to be supported i'm afraid.

**Comment by philippemercure** [comment]
I see. Since the verb was available here : https://fast-endpoints.com/api/FastEndpoints.Http.html?q=POST, I assume something could be done to bypass the limitation.

I’m no expert in this, but wouldn’t one of those 2 versions could be support in Minimal API, since both were update in the last couple of days and thus, in FastEdnpoint shortly?

Version 6.0.3 ; https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/
Version 7.0.0 ; https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/7.0.0-preview.2.22153.2

I couldn’t find any info of Minimal API and Patch. Except in here : https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio#differences-between-minimal-apis-and-apis-with-controllers

Stating : No support for [JsonPatch](https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/)

Knowing what you know, would you use the Controller way in the same project as FastEndpoint if a Patch endpoint would be required by your design right now? Or still use Put, change your design for now and wait for a proper Patch implementation in Minimal API then FastEndpoint.

Thanks a lot.

**Comment by dj-nitehawk** [comment]
if you can't wait until `System.Text.Json` supports JsonPatch, you can use the following slightly hacky workaround which uses plain text binding:
```csharp
global using FastEndpoints;
using FastEndpoints.Swagger;
using Microsoft.AspNetCore.JsonPatch;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

public class User
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class PatchRequest : JsonPatchDocument<User>, IPlainTextRequest
{
    public int UserID { get; set; }

    public string Content { get; set; }

    public JsonPatchDocument<User> PatchDocument
        => Newtonsoft.Json.JsonConvert.DeserializeObject<JsonPatchDocument<User>>(Content)!;
}

public class PatchUser : Endpoint<PatchRequest>
{
    public override void Configure()
    {
        Patch("test/{UserID}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(PatchRequest req, CancellationToken ct)
    {
        var user = new User { Id = req.UserID, FirstName = "first", LastName = "last" };

        req.PatchDocument.ApplyTo(user);

        await SendAsync(user);
    }
}
```
http patch request body:
```json
[
    {
        "path": "/firstName",
        "op": "replace",
        "value": "Fast"
    },
    {
        "path": "/lastName",
        "op": "replace",
        "value": "Endpoints"
    }
]
```

**Comment by dj-nitehawk** [comment]
to be able to get swagger to generate the correct document `jsonpatchdocument`, we're gonna need the nswag version of something like this: https://stackoverflow.com/a/65607728/4368485

could someone seeing this possibly port the above to a nswag document processor?

**Comment by philippemercure** [comment]
Thanks dj-nitehawk, I was able to make everything work with your provided example. I also managed to make the  Swagger documentation reflect a JsonPatchDocument.

I use this OperationProcessor in the AddSwaggerDoc

```c#
serviceCollection.AddSwaggerDoc(settings =>
{
    settings.OperationProcessors.Add(new PatchOperationProcessor());
}
```

And this class to make to request body appear in the Swagger Documentation

```c#
public class PatchOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        // Return false to exclude am operation from the document
        
        if (context.OperationDescription.Method != "patch")
        {
            return true;
        }
        
        const string example = "[ { \"path\": \"/a-path\",\"op\": \"replace\",\"value\": \"A replacement value\" },{ \"path\": \"/another-path\",\"op\": \"remove\" }]";
            
        context.OperationDescription.Operation.Parameters.Add(new OpenApiParameter
        {
            Kind = OpenApiParameterKind.Body,
            IsRequired = true,
            Schema = JsonSchema.CreateAnySchema(),
            Example = example
        });
            
        return true;
    }
}
```

The example is not automatic, but it's generic enough for my use case.

Screenshot of Swagger Documentation :
<img width="1439" alt="Screen Shot 2022-03-29 at 01 37 20" src="https://user-images.githubusercontent.com/4966091/160540819-e7097232-094f-4402-a28c-92f6f70fc192.png">

Thanks a lot for your help, :).

**Comment by dj-nitehawk** [comment]
awesome!!! i'll see if i can incorporate it in v4.1 as 4.0 is already baked in and getting released today 👍

**Comment by jorge-ribeiro-evaltec** [comment]
@dj-nitehawk 

In case it's useful for including this in the library, I improved the PatchOperationProcessor a bit, based on the stackoverflow answer:
```csharp
public class PatchOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        // Return false to exclude an operation from the document
        
        if (context.OperationDescription.Method != "patch")
        {
            return true;
        }

        // Remove internal schemas generated from the type JsonPatchDocument<T>
        var schemas = context.Document.Components.Schemas.ToList();
        foreach (var item in schemas)
        {
            if (item.Key.StartsWith("OperationOf", StringComparison.Ordinal) ||
                item.Key.StartsWith("JsonPatchDocumentOf", StringComparison.Ordinal))
                context.Document.Components.Schemas.Remove(item.Key);
        }

        if (!context.Document.Components.Schemas.ContainsKey("Operation"))
        {
            context.Document.Components.Schemas.Add("Operation",
                new JsonSchema()
                {
                    Type = JsonObjectType.Object,
                    Properties =
                    {
                        { "op", new JsonSchemaProperty() { Type = JsonObjectType.String } },
                        {
                            "value", new JsonSchemaProperty { Type = JsonObjectType.Object, IsRequired = false }
                        },
                        { "path", new JsonSchemaProperty { Type = JsonObjectType.String } }
                    }
                });
        }

        if (!context.Document.Components.Schemas.ContainsKey("JsonPatchDocument"))
        {
            context.Document.Components.Schemas.Add("JsonPatchDocument",
                new JsonSchema()
                {
                    Type = JsonObjectType.Array,
                    Item = new JsonSchema() { Reference = context.Document.Components.Schemas["Operation"] }
                });
        }

        // remove the accepted type text/plain in case it exists - due to the 'hack' with IPlainTextRequest
        context.OperationDescription.Operation.Consumes.Remove("text/plain");

        var example =
            "[ { \"path\": \"/a-path\",\"op\": \"replace\",\"value\": \"A replacement value\" },{ \"path\": \"/another-path\",\"op\": \"remove\" }]";

        context.OperationDescription.Operation.Parameters.Add(new OpenApiParameter
        {
            Kind = OpenApiParameterKind.Body,
            IsRequired = true,
            Schema = context.Document.Components.Schemas["JsonPatchDocument"],
            Example = example
        });
            
        return true;
    }
}
```

I am also thinking of generating relevant examples for the type - let me know if it would be useful and I can help implement this.

**Comment by philippemercure** [comment]
Hello @jorge-ribeiro-evaltec, I'm just wondering if your modification to the PatchOperationProcessor was test?

On my end, I was not able to make your solution work, even if I try to modify some lines in your provided code.

I can see that you are trying to remove those 2 Schemas.

<img width="725" alt="Screen Shot 2022-04-07 at 16 16 15" src="https://user-images.githubusercontent.com/4966091/162288987-ad1b3a32-fa3d-44d4-9589-bba647932ca0.png">

But I can understand why since, first it was already working (could you explain what you want to do with this modification?) and second why not remove the Operation schema as well, so that you would have only the one you are trying to add here.

Waitings news.

Thanks a lot.

**Comment by jorge-ribeiro-evaltec** [comment]
Hi, @philippemercure,

In my case there were some other problems going on with generics - but I can't reproduce them anymore.

In the end I decided to replace these schemas anyway because we use auto-generated clients based on the swagger definition, and these schema definitions were simply wrong:

![image](https://user-images.githubusercontent.com/91900462/162310853-c41c27e8-adac-474d-9494-3b8770f9c506.png)

As you can see in the screenshot above, there is a wrapper around the array of operations and there are some internal types exposed.

With the processor I adapted from stackoverflow I now get the following definition:
![image](https://user-images.githubusercontent.com/91900462/162313008-7ea2f67b-4793-477d-b67f-76d1f7fe8ba5.png)

The schema now uses a generic Operation and I didn't use an enum (maybe I'll update to use the correct enum in the future) but for our use case it is enough.

**Comment by jorge-ribeiro-evaltec** [comment]
But yes, @philippemercure it is working for me.

I'm using FastEndpoints 4.0 and I have these imports for this class:

```csharp
using NJsonSchema;
using NSwag;
using NSwag.Generation.AspNetCore;
using NSwag.Generation.Processors;
using NSwag.Generation.Processors.Contexts;
```
